---
- name: Setup Apache, PHP, and MySQL
  hosts: all
  become: yes
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Install PHP
      apt:
        name: php
        state: present

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Start and enable Apache2
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Start and enable MySQL
      service:
        name: mysql
        state: started
        enabled: yes
